# Generated by Django 5.2 on 2025-12-24 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='note',
            new_name='api_note_updated_bb4af1_idx',
            old_name='api_note_upd_idx',
        ),
        migrations.RenameIndex(
            model_name='note',
            new_name='api_note_title_4e44df_idx',
            old_name='api_note_tit_idx',
        ),
    ]
